config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'records#index'
  resources :records
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/record.rb
# frozen_string_literal: true

class Record < ApplicationRecord
  enum :grade, %i[first pre_first second pre_second third fourth fifth], suffix: true
  enum :first_stage, %i[pass fail exemption], suffix: true
  enum :second_stage, %i[pass fail], suffix: true
  enum :result, %i[pass fail], suffix: true

  validates :test_date, presence: true
  validates :grade, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/records_controller.rb
# frozen_string_literal: true

class RecordsController < ApplicationController
  def index
    @records = Record.order(:created_at)
  end

  def show
    set_record
  end

  def new
    @record = Record.new
  end

  def edit
    set_record
  end

  def create
    @record = Record.new(record_params)

    if @record.save
      redirect_to @record
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    set_record

    if @record.update(record_params)
      redirect_to @record
    else
      render 'update', status: :unprocessable_entity
    end
  end

  def destroy
    set_record
    @record.destroy
    redirect_to records_path, status: :see_other
  end

  private

  def record_params
    attributes = %i[test_date grade first_stage second_stage result reading writing listening speaking]
    params.require(:record).permit(*attributes)
  end

  def set_record
    @record = Record.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title EikenRecords
    meta name='viewport' content='width=device-width,initial-scale=1'
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags

  body
    = yield

app/views/records/_form.html.slim
= form_with model: record do |f|
  div
    = f.label :test_date, Record.human_attribute_name('test_date')
    = f.date_field :test_date

  div
    = f.label :grade, Record.human_attribute_name('grade')
    = f.select :grade, [%w[一級 first],
                        %w[準一級 pre_first],
                        %w[二級 second],
                        %w[準二級 pre_second],
                        %w[三級 third],
                        %w[四級 fourth],
                        %w[五級 fifth]]

  div
    = f.label :first_stage, Record.human_attribute_name('first_stage')
    = f.select :first_stage, [%w[合格 pass], %w[不合格 fail], %w[免除 exemption]]

  div
    = f.label :second_stage, Record.human_attribute_name('second_stage')
    = f.select :second_stage, [%w[合格 pass], %w[不合格 fail]]

  div
    = f.label :result, Record.human_attribute_name('result')
    = f.select :result, [%w[合格 pass], %w[不合格 fail]]

  div
    = f.label :reading, Record.human_attribute_name('reading')
    = f.text_field :reading

  div
    = f.label :writing, Record.human_attribute_name('writing')
    = f.text_field :writing
  div
    = f.label :listening, Record.human_attribute_name('listening')
    = f.text_field :listening
  div
    = f.label :speaking, Record.human_attribute_name('speaking')
    = f.text_field :speaking

  = f.submit button_text

app/views/records/edit.html.slim
h1 記録編集

= render partial: 'form', locals: { record: @record, button_text: '更新' }

app/views/records/index.html.slim
h1 #{Record.model_name.human}一覧

- if @records
  ul
    - @records.each do |record|
      li
        = link_to "#{t(record.grade)} (#{record.test_date})", record

= link_to '記録作成', new_record_path

app/views/records/new.html.slim
h1 記録作成

= render partial: 'form', locals: { record: @record, button_text: '作成' }

app/views/records/show.html.slim
h1 #{Record.model_name.human}詳細

ul
  li #{Record.human_attribute_name('test_date')} : #{@record.test_date}
  li #{Record.human_attribute_name('grade')} : #{t(@record.grade)}
  li #{Record.human_attribute_name('first_stage')} : #{t(@record.first_stage)}
  li #{Record.human_attribute_name('second_stage')} : #{t(@record.second_stage)}
  li #{Record.human_attribute_name('result')} : #{t(@record.result)}
  li #{Record.human_attribute_name('reading')} : #{@record.reading}
  li #{Record.human_attribute_name('writing')} : #{@record.writing}
  li #{Record.human_attribute_name('listening')} : #{@record.listening}
  li #{Record.human_attribute_name('speaking')} : #{@record.speaking}

p = link_to "#{Record.model_name.human}一覧", records_path

p = link_to '編集', edit_record_path(@record)

p = link_to '削除', @record, data: { turbo_method: :delete,
                                    turbo_confirm: '本当に削除しますか？' }